// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF-L9DFfYhkulJolhGa2cC_hipwhPkmZc',
    appId: '1:980861028912:web:07a4e6af6f5532441c3bf5',
    messagingSenderId: '980861028912',
    projectId: 'reddit-clone-c2bd4',
    authDomain: 'reddit-clone-c2bd4.firebaseapp.com',
    storageBucket: 'reddit-clone-c2bd4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVXzA9cp_jUGTzHufH8XYSAjWf5bWPGdg',
    appId: '1:980861028912:android:ca12745fc6efe7c91c3bf5',
    messagingSenderId: '980861028912',
    projectId: 'reddit-clone-c2bd4',
    storageBucket: 'reddit-clone-c2bd4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKpCLnxINh2EspXe7Regu3GxNAxwemxHE',
    appId: '1:980861028912:ios:1b83f3816d88e3df1c3bf5',
    messagingSenderId: '980861028912',
    projectId: 'reddit-clone-c2bd4',
    storageBucket: 'reddit-clone-c2bd4.appspot.com',
    iosClientId: '980861028912-ctm4legtl27ktbaichik541e8eq3aegk.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );
}
